export const ExperimentReducerTypes = {
    resetConfig: 'resetConfig',
    setExperimentName: 'setExperimentName',
    setRepetitions: 'setRepetitions',
    setNetworkSize: 'setNetworkSize',
    setSeedSize: 'setSeedSize',
    setPeriods: 'setPeriods',
    setDescription: 'setDescription',
    setEssentialData: 'setEssentialData',
    setDetailedData: 'setDetailedData',
    setExperimentType: 'setExperimentType',
    deleteAgentConfig: 'deleteAgentConfig',
    addAgentConfig: 'addAgentConfig',
    updateAgentConfig: 'updateAgentConfig',
    updatePercentageAgentConfig: 'updatePercentageAgentConfig',
    updateSeedAgentConfig: 'updateSeedAgentConfig',
};